# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine :
    resolvers :
        galerie_images_cache:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "img/indatabase/galerie/cache"
        publication_images_cache:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "img/indatabase/publication/cache"
        carrousel_images_cache:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "img/indatabase/carrousel/cache"
        kiosque_images_cache:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "rsc/indatabase/kiosque/thumbnails/cache"

    filter_sets :
        cache: ~
    
    # Carrousel
        
        carrousel_home:
            cache: carrousel_images_cache
            quality : 80
            filters:
                fixed:
                    width: 1110
                    height: 370
        carrousel_cover_index_thumb:
            cache: carrousel_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 300, 200 ]
        carrousel_cover_edit:
            cache: carrousel_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 600, 300 ]    
        carrousel_title_edit:
            cache: carrousel_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 1000, 500 ]       

    # Publication
        
        publication_thumb:
            cache: publication_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 550, 350 ]            
        publication_cover_index_thumb:
            cache: publication_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 300, 200 ]
        publication_cover_edit:
            cache: publication_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 600, 300 ]    
        publication_title_edit:
            cache: publication_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 1000, 700 ]

    # Galerie
           
        galerie_thumb:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 550, 350 ]                 
        galerie_content_edit:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 600, 800 ]
        galerie_cover_index_thumb:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 300, 200 ]
        galerie_cover_edit:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 600, 300 ]
        galerie_title_edit:
            cache: galerie_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 1000, 500 ]

    #kiosque
    
        kiosque_index_thumb:
            cache: kiosque_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 200, 250 ]
        
        kiosque_home_thumb:
            cache: kiosque_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 250, 320 ]
        
        kiosque_thumb:
            cache: kiosque_images_cache
            quality : 80
            filters:
                scale:
                    dim: [ 300, 400 ]